pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        GIT_REPO_URL = 'https://github.com/Angurajnagaraj/new-test/'  // Your GitHub repository URL
        BRANCH_NAME = 'main'  // Branch you want to checkout, change as needed
	DOCKER_CREDENTIALS = credentials('DockerId')
	GITACCESS = credentials('Githubaccesstoken')
	GIT_REPO_NAME = "cicd-demo-manifests-repo"
        GIT_USER_NAME = "Angurajnagaraj"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git url: "${GIT_REPO_URL}", branch: "${BRANCH_NAME}"
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    cd python-web-app
                    cat Jenkinsfile
                    echo 'Buid Docker Image'
                    docker build -t angurajnagaraj/python-web-app:${BUILD_NUMBER} .
                    '''
                }
            }
        }
		
        stage('Login to Docker Hub') {
            steps {
                script {
                    sh "echo \$DOCKER_CREDENTIALS_PSW | docker login -u \$DOCKER_CREDENTIALS_USR --password-stdin"
                }
            }
        }
		
	stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push angurajnagaraj/python-web-app:${BUILD_NUMBER}
                    '''
                }
            }
        }
		
     stage('Checkout K8S manifest SCM'){
            steps {
                git url: 'https://github.com/Angurajnagaraj/cicd-demo-manifests-repo',
                branch: "${BRANCH_NAME}"
            }
        }
		
	stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([string(credentialsId: 'Githubaccesstoken', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                        cat deploy.yaml
                        sed -i 's/17/${BUILD_NUMBER}/g' deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
			//git push https://github.com/Angurajnagaraj/cicd-demo-manifests-repo.git HEAD:main
   			git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                        '''                        
                    }
                }
            }
        }
        
    }
}
